### ISSUE TITLE
Access WAS apps in q1 and q2

### ISSUE THREAD

**Issue by eirslett** [nais/device#101]
All WAS apps in q1 and q2 are on `https://wasapp-q1.adeo.no/` and `https://wasapp-q2.adeo.no/`. These are all supposed to have synthetic test data.

**Comment by jhrv** [comment]
bestilling sendt https://jira.adeo.no/plugins/servlet/desk/portal/542/IKT-203981

**Comment by jhrv** [comment]
q1 contains sensitive data

**Comment by jhrv** [comment]
q2 is ok 👌
