### ISSUE TITLE
Auto-connect for device agent

### ISSUE THREAD

**Issue by magnuvau** [nais/device#106]
Add (when do-able) feature to auto-connect the device agent for a more seamless startup.

**Comment by jhrv** [comment]
The "connect" performs the AAD auth flow which opens the browser to communicate the authorization code from Azure. A auto-connect feature then might suddenly open your browser at potentially inconvenient times. 

In addition we are looking to add another factor during connect/auth, using yubikey or authenticator app as the second factor. In light of this, it might not make sense with this feature.
