### ISSUE TITLE
Loggtuning

### ISSUE THREAD

**Issue by jhrv** [nais/device#109]
Lage stackdriver spørringer for

- når koblet device til hvilken gateway?
- hvilke devicer koblet til gateway x i tidsrom y
- når connectet bruker til naisdevice / logget inn
- har device vært unhealthy /  blitt frisk / statechange

For å se hvorvidt en device har koblet seg opp via en GW mot en intern tjeneste kan vi se på å bruke logger fra iptables og sende dette til stackdriver. src-ip til device er statisk

**Comment by x10an14** [comment]
- `når connectet bruker til naisdevice / logget inn` -> `apiserver`
   - Splittet ut i https://github.com/nais/device/issues/122
- `har device vært unhealthy / blitt frisk / statechange` -> `apiserver`
   - Gjort i: https://github.com/nais/device/blob/ca98fca8663a8c0f9b42b7a791b17491bfb68e25/device-health-checker/src/Command/CheckAndUpdateDevices.php#L46
   - Relatert: https://github.com/nais/device/issues/123
- `når koblet device til hvilken gateway?` -> `"gatewayene våre"` -> Sjekk ansible scripts
   - IP tables logdemo er utført, nå mangler å teste på en gateway.

_Oppdatert 16.09.2020_

**Comment by x10an14** [comment]
Demo proving iptables kernel-logging functionality
![Screenshot_ubuntu18 04_2020-09-14_09:54:15](https://user-images.githubusercontent.com/710608/93062804-b23a6780-f675-11ea-9865-e1c37308a089.png)

**Comment by x10an14** [comment]
Hvis 
1. https://github.com/nais/device/pull/124
2. og https://github.com/nais/device/pull/130
merges, så er denne oppgaven ferdigstilt.
