### ISSUE TITLE
Move binaries/install script to gcp bucket to avoid GitHub rate limit

### ISSUE THREAD

**Issue by sechmann** [nais/device#111]

**Comment by mortenlj** [comment]
Er ikke dette egentlig løst, ved at vi på mac og linux nå ikke lenger bruker install-scriptet, og har flyttet ting til nais/homebrew-tap og nais/nais-ppa repoene? I nais-ppa bruker vi dessuten Pages for å serve filene.

Ikke løst for windows da... som vanlig.

**Comment by sechmann** [comment]
Men planen for M$ er å flytte dette også vekk fra GitHub - lukker
