### ISSUE TITLE
Logge når bruker tilkobler enhet til naisdevice

### ISSUE THREAD

**Issue by x10an14** [nais/device#122]
Splittet ut fra #109 

### Status
Tilkobling blir logget av [denne linjen](https://github.com/nais/device/blob/e3c32893c9ae12302b22804802690374edde224a/apiserver/api/api.go#L156). Det som gjenstår er å bekrefte at den dukker opp i Google StackDriver/sikre at use-cases er dekket.

**Comment by x10an14** [comment]
Verifisert logget inn i console.cloud.google.com -> mangler nå å sikre use-cases.

**Comment by x10an14** [comment]
### Use-case fra @toby1knby 
- "Hvis noen har tatt en dump av postgres db'er, vil vi vite har vi noen koblinger ifbm. brukeren som har utført dumpen"?

### Use-case fra @jhrv 
- "Har bruker koblet til naisdevice og fått ned config for gateways", når bruker kobler til naisdevice, logg også hvilke gateways(m/config) som bruker mottar.

PS: Snakke med Terje & Marcel?

**Comment by x10an14** [comment]
Implementert.

Mangler å snakke med @terjesannum og Marcel.

**Comment by sechmann** [comment]
Er dette egentlig ferdig @x10an14 ? Skal vi booke en demo?

**Comment by x10an14** [comment]
Should've been closed with https://github.com/nais/device/issues/122#event-4011830747
