### ISSUE TITLE
Tilgang til ingresser i knada-clusteret

### ISSUE THREAD

**Issue by Kyrremann** [nais/device#128]
Ønsker tilgang til *.knada.adeo.no og *.jupyter.adeo.no. Nye egne ingresser for knada-clusteret i FSS prod. Må kanskje oppdatere ROS med at vi bruker naisdevice og har nye ingresser først.

**Comment by sechmann** [comment]
Løst

```
155.55.3.27    443/tcp   *.knada.adeo.no
155.55.3.2     443/tcp   *.jupyter.adeo.no
```
er lagt til gateway `155.55.64.70`

FW åpninger må dere bestille selv på gamlemåten
