### ISSUE TITLE
Tilgang til api-gateway

### ISSUE THREAD

**Issue by richardborge** [nais/device#134]
Hei. Det er ønskelig å få tilgang til `api-gw-q1.adeo.no` på naisdevice. Den er tilgjengelig fra utviklerimage. Vet ikke om det vil ha noe å si.

**Comment by sechmann** [comment]
This was forgotten. To complete this, whoever controls managed the access for this host needs to make the DNS entry part of public DNS:
```
% host api-gw-q1.adeo.no
Host api-gw-q1.adeo.no not found: 3(NXDOMAIN)
```

And open for traffic from: `155.55.64.82`

**Comment by ybelMekk** [comment]
host is `api-gw-q1.adeo.no` is synced with public dns. Need fw opening: https://jira.adeo.no/browse/ITIP-820

**Comment by ybelMekk** [comment]
FW is updated @Sechmann

**Comment by ybelMekk** [comment]
Denne skal vare mulig å åpne for nå?

**Comment by sechmann** [comment]
was done in july, in f1707814
