### ISSUE TITLE
Circular dependency on Linux client

### ISSUE THREAD

**Issue by chinatsu** [nais/device#137]
I'm creating this issue so that it's not forgotten. I sort of introduced the issue in #100, though I think what I did was a step in the right direction anyway, to create a distinction between the root-level `device-agent-helper`, and the user-level `device-agent`.

The stem of the issue is that the device serial on Linux is only readable as root, which is not the case (as far as I understand) on Mac or Windows.

In my PR, I removed the need for root in `device-agent` which it used solely to read the device serial, and moved that operation
to `device-agent-helper`. This reads `/sys/devices/virtual/dmi/id/product_serial` directly and stores the content to a file in the `cfg.ConfigPath` directory and makes that information readable for `device-agent`. 

The core of the problem here is that

*  `device-agent-helper` requires the config directory to exist in order to write the device serial, while 
* `device-agent` which has the responsibility to create the config directory (if it doesn't exist) requires the device serial to start.

**Comment by mortenlj** [comment]
We will solve this by moving the extraction of serial to a postinstall script delivered as part of the install package (#167).
