### ISSUE TITLE
Colour-coding in install-script does not work well on OS X

### ISSUE THREAD

**Issue by pjwalstrom** [nais/device#138]
comes out as plain text

```
curl https://device.nais.io/install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   991  100   991    0     0   3012      0 --:--:-- --:--:-- --:--:--  3012
##################################
# Installing naisdevice
##################################

determining latest version.....[\e[38;5;82mok\e[0;5;82m]
downloading latest pkg.........[\e[38;5;82mok\e[0;5;82m]
installing package.............[\e[38;5;82mok\e[0;5;82m]
```

**Comment by x10an14** [comment]
I think this depends on the terminal (and maybe also shell) used?

Ref: https://unix.stackexchange.com/a/4132

Could you add details of your shell/terminal?

**Comment by pjwalstrom** [comment]
yes, you are probably right! 

It is piped to bash, so I guess it is the bash-version that decides? OS X uses an ancient bash-version (https://itnext.io/upgrading-bash-on-macos-7138bd1066ba). OS X has changed the default shell to zsh (https://support.apple.com/en-us/HT208050), so if I pipe to zsh instead, it works fine. Anyway, I could upgrade my bash-version, but most Macs out there run the same ancient version (from 2007!)

``` 
➜  ~ bash -version                                
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.
➜  ~  
```

**Comment by x10an14** [comment]
I think we need more pressing requirements before we want to consider the technical effort of supporting coloring of 13-year old versions of BASH simultaneously with already working shells =)

Thanks for input, it is absolutely useful to have documentation of this behavior for posterity! =D
(Closing issue).

**Comment by pjwalstrom** [comment]
Fair enough, but I would assume removing the colour-coding would give an overall better user-experience on average. That would give the Mac-users with bash 3.2 (the majority?) some meaningful output, while everybody else would just loose the colours. But I agree, this is not a pressing requirement :-)
