### ISSUE TITLE
Tilgang til tjenester på Aiven

### ISSUE THREAD

**Issue by mortenlj** [nais/device#139]
Vi kjører Kafka på Aiven, og folk ønsker mulighet til å snakke med clusteret fra laptop. Tenker det er greit for dev i hvertfall.
Tilsvarende er det nyttig å kunne nå Prometheus portene, og nå har vi så smått begynt å se på å tilby Elastic. Alt dette hadde vært nyttig å kunne nå med naisdevice.

Aiven prosjektene er peeret med hensiktsmessige VPCer.

**Comment by mortenlj** [comment]
Elastic på Aiven kommer med Kibana ut av boksen, denne hadde vært nyttig å nå fra laptop også. Jeg tror en evt. løsning bør gjøre det mulig å nå alle tjenester som kjører på Aiven.

**Comment by mortenlj** [comment]
@Sechmann fixed this in https://github.com/nais/naisdevice-terraform/commit/0dfad3f625b55bd676a86aa4e50def89b197a8ce I believe.

**Comment by sechmann** [comment]
Re-fixed here: https://github.com/nais/naisdevice-terraform/commit/54f2ee79becd6bbcb847fbd4c98fd3438229a587
