### ISSUE TITLE
Support username changes

### ISSUE THREAD

**Issue by sechmann** [nais/device#146]
Users quite often change their emails, we should handle this.

As far as i can tell there are two possible solutions:
1. If a user logs in with an email that does not belong to any device, give a message back to the device-agent telling it to re-enroll.
2. Update the username for that serial in the database

**Comment by x10an14** [comment]
If I've understood your two suggestions correctly, there's a third one that might ease a lot of these(?) from the user's perspective;

1. Create a new db table correlating user ID with a osquery/kolide device ID.
2. Implement API(?) functionality that realizes; 
   - As long as a "new user" (read: email/nick/whatever changed) tries to connect with an existing osquery/kolide device ID, and everything else checks out, permit and update DB relation described in step 1.
3. This also provided benefit through giving us a  "log" of such changes.

Risk with approach: Someone already authenticated with naisdevice can go out of their way to guess/steal someone else's device ID, and thus "lock out" the original user of said device ID. Original user then needs to re-enroll "from scratch" to fix I'd guess.

**Comment by jhrv** [comment]
I think just giving the user feedback when we detect this during login, and point to a FAQ with instructions on how to force a re-enroll should be sufficient for this.

**Comment by sechmann** [comment]
> Create a new db table correlating user ID with a osquery/kolide device ID.

Using the _Kolide_ ID is a good idea, but i think we should keep it in the same table because `user<->naisdevice<->kolidedevice` is `1-1-1`.

Specifically i think we should:
1. Add `device_owner` to the `devices` table, containing the _Azure AD_ user object ID. Use this for verification instead of username.
2. Add `kolide_device_id` to the `devices` table, containing the same id that we get from the _Kolide_ API `/devices`.

To link a naisdevice with a _Kolide_ device we have a few options:
1. Find out the device ID from the _Kolide_ launcher and provide this during device-agent enroll
2. Keep sending serial/username to the `apiserver` and use this to find the device using the _Kolide_ API (preferably put this code in the `apiserver`)

Wen we have _Kolide_ ID in the `apiserver`, we can start using that in `device-health-checker`.

@christeredvartsen mentioned he wanted to implement this.

**Comment by x10an14** [comment]
> Using the Kolide ID is a good idea, but i think we should keep it in the same table because user<->naisdevice<->kolidedevice is 1-1-1.

Is this a guaranteed to remain true forever @VegarM? 
Even if it is as of right now, wouldn't implementing `check for X in list Y` be just as simple (and more future proof to implement) than `check if X equals Y`?

**Comment by Kyrremann** [comment]
Dere kan nå teste med meg!
Byttet fra kyrre.havik.eriksen@nav.no til kyrre.havik@nav.no

**Comment by Kyrremann** [comment]
Og kanskje fikse bedre feilmelding når man logger seg på?
```
failed logging in: reading session info from response body: EOF
```

**Comment by sechmann** [comment]
Removing the username from the `device-health-checker` logic and using Azure User Object ID in the apiserver would also solve this, and is way easier.
I consider using the `serial` and `kolide_device_id` to be the same. 

Let's start by implementing it this way.

**Comment by sechmann** [comment]
this works
