### ISSUE TITLE
Automatisk oppdatering

### ISSUE THREAD

**Issue by hakonph** [nais/device#148]
Hadde vert fint om naisdevice oppdaterete seg automatisk.
Eventuelt at man bare kunne trykket på knappen, i stedet for og kopierer kommandoen

**Comment by mortenlj** [comment]
På linux har vi nå en PPA. Hvis man samtidig kjører unattended-upgrades (noe man skal), så vil den oppdatere naisdevice automatisk.

På mac har vi brew. Brew må man kjøre oppdatering selv, men man kan helt sikkert få til å lage noe schedule-greier på den på mac...?

På windows er vi litt mer på bar bakke. Winget-greiene Microsoft kom med funka ikke helt for oss, men kan jo være noe vi skal se på igjen.. kanskje de har gjort det bedre?

Uansett, vil påstå at denne er løst for linux, så og si løst for mac, og dessverre ikke i nærheten for windows.

**Comment by mortenlj** [comment]
For en stund siden introduserte vi en scoop bucket for windows-brukere. Dermed er windows også nogenlunde løst.
Jeg tror jeg har lyst til å si at denne saken er løst.
