### ISSUE TITLE
Feedback pentest

### ISSUE THREAD

**Issue by jhrv** [nais/device#162]
- Stramme inn TLS ciphers for bootstrap-api, bruke samme ciphers vi har på L7 nais
- APIene apiserveren bruker mot bootstrap-api bør sjekke src ip og verifisere at det er apiserver
- Sjekke åpne porter i rapporten, verifisere at disse ikke er åpne/eksponert på boksen, men er fra Google LB

**Comment by sechmann** [comment]
This was done a long time ago.
