### ISSUE TITLE
Clean up routes when tunnel is not working

### ISSUE THREAD

**Issue by sechmann** [nais/device#17]
Currently, if the tunnel stops working it will end up in a never ending loop because:
- We add routes that tunnel *Microsoft*-traffic through a gateway
- We use azure ad auth on our api server

In the scenario where the microsoft gateway stops working, we're unable to fetch new access tokens, and therefore unable to communicate with the api.

**Comment by jhrv** [comment]
suggestion:
```
c, err := getConfig(apiserver)
if err != nil {
    cancel() // ctx that stops device-agent-helper (will clean up routes)
    // overwrite wg0.conf with bootstrap config 
    // restart helper
} 
...
```
