### ISSUE TITLE
I am able to reach dev.nav.no ingresses after restart before naisdevice is started

### ISSUE THREAD

**Issue by heyvard** [nais/device#173]
Steps to reproduce:

1. Connect naisdevice
2. Open https://flex-docs.dev.nav.no/ in chrome
3. Shutdown macbook
4. Turn macbook on
5. Do not start naisdevice app
6. It is possible to open https://flex-docs.dev.nav.no/ 
7. Start naisdevice app, do not connect
8. https://flex-docs.dev.nav.no/ is not reachable
9. connect naisdevice and restart chrome
10. https://flex-docs.dev.nav.no/ is reachable

Is it any caching of DNS or something left after restart? Might be an issue?

**Comment by sechmann** [comment]
Good catch, this is due to the fact that the underlying WireGuard VPN will keep its previous configuration and we've not yet implemented short lived credentials and rotation of keys: https://github.com/nais/device/issues/150

**Comment by sechmann** [comment]
fixed "client-side" by https://github.com/nais/device/commit/a73408f9c90df793e2587e9e4d86353aae269472, which gives better UX. Server-side the configuration is still valid for the entire session duration. Short-lived sessions tracked in #150
