### ISSUE TITLE
Mulig problem med ny default installasjonsmetode av Firefox i Ubuntu LTS 22.04: Access to Office Portal is blocked

### ISSUE THREAD

**Issue by ahusby** [nais/device#202]
Ny default installasjonsmetode i Ubuntu blir snap, ref: https://www.omgubuntu.co.uk/2021/09/ubuntu-makes-firefox-snap-default
Jeg (med flere) har hatt sertifikatproblmer som gjorde at jeg ikke kom inn på Navet og Onedrive. Fikk "Access to Office Portal is blocked". Fiksen i denne tråden virket ikke for meg før jeg reinstallerte Firefox med deb (apt-kommandoen), snap-variante funket ikke: https://nav-it.slack.com/archives/C02983C4L01/p1634292923157900

**Comment by sechmann** [comment]
vi har lagt inn snap nssdb i cert enroll koden, det skal funke nå
