### ISSUE TITLE
Linux Kolide installer som jeg får i Slack tåler ikke reboot av laptopen rett etter installering

### ISSUE THREAD

**Issue by ahusby** [nais/device#211]
Nå har jeg gjort samme dumme feil to ganger på to forskjellige maskiner. Det er sikkert bare jeg som klarer å få dette problemet, så denne issue bør sikkert ikke ha så høy prioritet. Greit for meg om den lukkes uten noen action.

Saken er: Jeg skal installere Linux. Følger selvfølgelig nais-docen, til jeg får en deb-pakke i Kolide i Slack. Installerer den deb-en. Tar så umiddelbart en reboot av OS-et, før Kolide har rukket å detektere min nye maskin. Dette fører til at Kolide tilsynelatende aldri klarer å detektere min nye maskin etter restarten, unasett hvor lenge jeg venter.

Løsningen: Jeg avinstallerte deb-en, installerte den på nytt og tok hendene vek fra tastaturet og lot maskina være i fred. Da tok det bare et par minutter før jeg fikk en melding i Slack/Kolide som sier "We found a device that looks like it belongs to you!", som er det vi forventer.

Grunnen til at jeg har rebootet har vært at jeg har tenkt at det er sunt å ta en reboot etter å ha oppdatert alt rett etter installasjon av OS-et. Det er sikkert ikke nødvendig i det hele tatt, jeg har bare stukket en kjepp i mitt eget hjul :clown_face:

**Comment by sechmann** [comment]
Ja, dette er jo litt uheldig men lite vi kan gjøre noe med egentlig :man_shrugging:
Som du selv sier er det skjeldent du trenger en reboot med mindre du får beskjed om det :smile:
