### ISSUE TITLE
naisdevice - tvinge innlogging en gang om dagen f.eks.

### ISSUE THREAD

**Issue by ybelMekk** [nais/device#226]
nå er man logga inn leeeeenge

vi hadde noe funksjonalitet for dette før - men det er tydeligvis fjerna.

**Comment by sechmann** [comment]
Ganske sikker på at naisdevice session bare er 10 timer. Mener du trigge ny Azure AD login?

**Comment by ybelMekk** [comment]
@tommytroen ☝️😊, lagde denne fra github boardet til core

**Comment by frodesundby** [comment]
Nå kommer vi rett inn på alle gateways uten noen videre seremoni.
Dette er ikke helt heldig om et device skulle bli borte.
Vi bør undersøke mulighet for å tvinge innlogging daglig.

**Comment by thokra-nav** [comment]
Usikker på hva denne oppgaven er, men min opplevelse etter helga nå stemmer med teorien til @Sechmann. Åpnet naisdevice før jeg logget inn noe som helst sted og kom rett gjennom. 

Så er oppgaven å endre naisdevice-azure-appen til å tvinge passord hver dag?

**Comment by ybelMekk** [comment]
1. Vegar sier 10 timer er en `session`, dette stemmer etter 10 timer så gjør device en re-authenticate 
2. Jeg kan ikke se hva `device` sin application er konfigurert med då jeg ikke har tilgang

Vi vill  trigge en ny innlogging hvis sessionen i Azure AD appen har gått ut, eller der det device som bestemmer dette etter 10 timer?

Hvis vi bytter tenant så skal vi logge oss på på nytt uansett?
Vill ikke dette skape mye hovedbry?

Ettersom Device gjør en re-authenticate hver 10 time så sjekker den om bruker har en gyldig session. 

Slik Microsoft definerer det er jeg ganske enig i:

```
The Azure AD default configuration comes down to “don’t ask users to provide their credentials 
if security posture of their sessions hasn't changed”.
```

og 

```
Asking users for credentials often seems like a sensible thing to do, but it can backfire: 
users that are trained to enter their credentials without thinking can unintentionally
supply them to a malicious credential prompt.
```

Dev kluster onprem -> 10 timmer re-authenticate 
Prod onprem -> JITA

Gcp
Håndterer Google et aktivt forhold til bruker som må bekrefte innlogging.

**Comment by ybelMekk** [comment]
Har mistet tilgangen til Azure pga certifikat

**Comment by ybelMekk** [comment]
har ventende status, til det er avklart hva som skjer med naisdevice vidare
