### ISSUE TITLE
Multi-tenant naisdevice

### ISSUE THREAD

**Issue by jhrv** [nais/device#238]
De som jobber med plattformen ofte behov for å være tilkoblet flere tenants i sitt daglige virke. I noen oppgaver blir det mye hopping frem og tilbake, og i feilsituasjoner som oppstår må man gjerne switche til en annen tenant for å sammenligne oppsett etc. 

For de som har tilgang til mer enn én tenant (kun naisteamet) hadde det der vært praktisk å kunne koble på flere tenants samtidig. Siden det er utfordring med potensielt overlappende IP-adresser foreslås det at man begrenser multi-tilkoblingen til følgende tenants:

- nais.io
- dev-nais.io
- NAV + / nav.no

Fasit kjører også i nais.io, og det hadde vært fint å slippe  dagens løsning som åpner for hjemme-IPen til hver enkelt i Cloud Armor.

**Comment by jhrv** [comment]
Et forslag er å:
- Når naisadmins kobler til, kobler man automatisk til nais.io og dev-nais.io, mens for vanlige tenants (nav.no,mattilsynet, ssb etc er det kun én av gangen)

**Comment by thokra** [comment]
Dette hadde vært digg, men det jeg husker fra tidligere eksperimentering: 
- Det krever en større endring i hvordan naisdevice fungerer for å støtte flere tenants samtidig
  - Det er i dag vanskelig å støtte flere nettverk
- IP plan blir mer krevende, og vi må da unngå at en tenant kolliderer med nais.io og dev-nais.io.

Personlig så tenker jeg at dev-nais.io bør håndteres på samme måte som en vanlig tenant.

**Comment by jhrv** [comment]
> Personlig så tenker jeg at dev-nais.io bør håndteres på samme måte som en vanlig tenant.

Hvorfor? 



hvis dev-nais er egen tenant, og nav er egen tenant - er vi i praksis akkurat like langt når ipen er lagt inn i cloud armor.

Er ikke enig i at dette er en egen tenant da det både har CI miljøene våre og er der man jobber under utvikling. Å kunne gå dit samtidig som man er i en ekte tenant tror jeg er nyttig.

**Comment by thokra-nav** [comment]
For meg er dev-nais et dårligere CI miljø dersom vi spesialhåndterer det. Argumenterer ikke imot at det kan være nyttig

**Comment by thokra-nav** [comment]
Med de andre endringene som ble gjort tidligere, så tenker vi at problemet er redusert nok til av i lukker denne. Åpnes ved behov.
