### ISSUE TITLE
rpc error: code = Canceled desc = context canceled

### ISSUE THREAD

**Issue by Starefossen** [nais/device#240]
Denne feilmeldingen kommer av og til som en notifikasjon, den er ikke spesielt
hjelpsom. Hvis noen ™️  kan peke på hvor jeg kan finne hvor denne kommer fra så kan
jeg se på om jeg kan lage en bedre feilmelding.

<img width="365" alt="Screenshot 2022-12-17 at 21 36 00" src="https://user-images.githubusercontent.com/968267/208265280-c581bb22-802f-427b-ba53-a0d60bf6f867.png">

**Comment by ybelMekk** [comment]
@Starefossen 

das.rc.Tokens, err = auth.GetDeviceAgentToken(ctx, oauth2Config, das.Config.GoogleAuthServerAddress)

is select:

```
	select {
	case <-ctx.Done():
		return nil, fmt.Errorf("authFlow: %w", ctx.Err())
```

**Comment by ybelMekk** [comment]
Hmm, kanskje helt riktig, men også et sted hvor det trenges bedre error håndtering, tilbake til brukere

**Comment by ybelMekk** [comment]
nå så

må komme fra denne funksjonen:

`das.DeviceHelper.Teardown(ctx, &pb.TeardownRequest{})`

hvor det sen propageres

```
	if err != nil {
		notify.Errorf(err.Error())
	}
```

**Comment by frodesundby** [comment]
https://github.com/nais/device/pull/243

**Comment by ybelMekk** [comment]
har en ventede status tils vi vet hva som skjer med naisdevice tils vidare
