### ISSUE TITLE
naisdevice: lokal dns

### ISSUE THREAD

**Issue by frodesundby** [nais/device#255]
Det er fler som har tatt kontakt fordi de ikke kommer frem til *.intern.dev.nav.no.
Årsaken er at internettleverandøren sperrer oppslag som resolver til rfc 1918-adresser i DNS.
Midlertidig løsning er å legge til det man trenger i /etc/hosts

Naisdevice bør gjøre resolving av sine egne adresser, slik at man ikke må legge inn innslag manuelt.

**Comment by christeredvartsen** [comment]
Fixed using split DNS: 577c2b94a440478c17004b70ae9ae1ee9bf36e01
