### ISSUE TITLE
Publiseringsjobber feiler

### ISSUE THREAD

**Issue by jksolbakken** [nais/device#266]
Workflowene som publiserer ny klient til Homebrew, Scoop og PPA feiler ofte fordi de startes ogaå når de ikke burde ha vært startet. De trenger kun å kjøres når det faktisk har blitt gjort en release.

**Comment by sechmann** [comment]
fixed https://github.com/nais/device/commit/0261d22e0b3d78cf1bc75710bf675f9a912b6f6b
