### ISSUE TITLE
cache tokens (only refresh token?) to disk to avoid reauth every startup

### ISSUE THREAD

**Issue by jhrv** [nais/device#31]

**Comment by frodesundby** [comment]
https://github.com/nais/device/commit/97c909c93600645aeab36daf78d2651d01a8bd0e

**Comment by jhrv** [comment]
In addition to verifying that the file is present, we have to verify that the refresh token isn't expired

**Comment by jhrv** [comment]
token should be stored in `cfg.ConfigDir`
