### ISSUE TITLE
Refactor device-agent EventLoop

### ISSUE THREAD

**Issue by sechmann** [nais/device#338]
WIP

Investering: 2 mann, 3 uker

Dagens EventLoop i naisdevice device-agent har ballet på seg over noen år og er meget komplisert. Det gjør endringer svært vanskelig og fører ofte til bugs som treffer brukerne våre.

På det verste er det 8 ledd med indentation i EventLoop koden. Målet er å minimum halvere dette.
Det er også en funksjon på 269 linjer. Målet er å splitte denne opp i funksjoner på rundt 50 linjer hver. Disse skal ha tester.

At EventLoop er såpass vanskelig å jobbe med fører til:
- at folk vegrer seg for å oppdatere naisdevice fordi det er blitt vant med at ting ofte brekker.
- at vi havner i tilstander som er veldig vanskelig å feilsøke, "reboot" har blitt et vanlig løsningsforslag.
- det er veldig vanskelig å teste

Målet med dette initiativet er å stabilisere naisdevice for brukerne, samt gjøre det lettere å drive videre utvikling.

Non-goals

    RuntimeConfig bør ikke tukles med med mindre det er absolutt nødvendig.
    helper
    systray
    controlplane
    observability
    resten av device-agent koden

Det som er viktig for løsningen er at det er klart definert hvilke tilstander man kan være i og hvilke hendelser som endrer den tilstanden.

Vi ser for oss følgende tilstander (men det er ikke et must):

```mermaid
graph TD;
    disconnected-->authenticating;
    authenticating-->bootstrapping;
    bootstrapping-->connected;
    connected-->disconnected;
    authenticating-->disconnected;
    bootstrapping-->disconnected;
```

Inspirasjon kan tas herifra, selv om vi misstenker at eksemplet er litt for enkelt: https://www.iamyadav.com/blogs/implementing-a-simple-state-machine-in-golang
En branch med utforskende kode er tilgjengelig, men trenger ikke være basis for en eventuell løsning:
https://github.com/nais/device/pull/345

**Comment by jhrv** [comment]
Er denne ferdig?

**Comment by sechmann** [comment]
Nei, vi skal release den før vi lukker lappen bare.
