### ISSUE TITLE
Access to NAIS-services

### ISSUE THREAD

**Issue by jhrv** [nais/device#65]
services:
  - stash.adeo.no -> 155.55.191.66
  - repo.adeo.no -> 155.55.191.17
  - vault.adeo.no -> 155.55.2.55
  - basta.adeo.no -> 34.107.200.188
  - fasit.adeo.no -> no public record, needs bigip
  - vera.adeo.no -> 155.55.191.40
  - \*.dev-gcp.nais.io -> 35.201.69.142 
  - \*.prod-gcp.nais.io -> 34.98.72.221
  - \*.dev.nav.no -> 35.190.76.128
  - \*.dev.adeo.no -> 35.190.123.235

for each service ensure:
  - GW that fits location and permissions
  - LB presenting a valid certificate for the service
  - ensure connection/FW gw -> LB
  - add routes to gateway object
  - add iptables rule to allow and SNAT requests
  - public dns record pointing to the LB

**Comment by sechmann** [comment]
basta needs a gateway in prod-gcp

**Comment by jhrv** [comment]
`nais-gcp-services` perhaps?

**Comment by jhrv** [comment]
@matsbyfl had some concerns about opening Fasit. We should have a internal discussion and make sure we are comfortable with doing so.

**Comment by jhrv** [comment]
we should also be able to reach services in the different clusters exposed on `<cluster>.nais.io` such as alertmanager and prometheus

**Comment by jhrv** [comment]
> @matsbyfl had some concerns about opening Fasit. We should have a internal discussion and make sure we are comfortable with doing so.

We agreed Fasit was OK to open

**Comment by jhrv** [comment]
updated status:

missing correct certs for dev.{nav,adeo}.no
missing public dns records for most services
