### ISSUE TITLE
Allowlist of serials (e.g. only NAV-machines, or other approved devices)

### ISSUE THREAD

**Issue by jhrv** [nais/device#71]
As a administrator it should be possible to only allow devices from a list serials

**Comment by toby1knby** [comment]
In progress IKT-208941

**Comment by sechmann** [comment]
skjer det noe her @toby1knby ?

**Comment by toby1knby** [comment]
Ja, og nei. Det å få ut en masterliste av interne systemer er mye løfting og mange kokker. Hvis vi uansett skal tilby "BYOD" (ref. initiativ i Azure-gjengen) så opplever jeg det som bortkastet tid, og hadde lyst til å se om funksjonaliteten er/blir overflødig. I mellomtiden så kjører jeg vaktmester på å følge opp dette (Når det dukker opp maskiner som ikke er våre.

**Comment by toby1knby** [comment]
Update: 

1. Windowsmaskiner er tatt hånd om. Det må være en NAV enhet for å ikke feile Kolide-sjekke om MDM. Man får ikke rullet inn non-NAV Windows maskiner i Intune.
2. Mac kan vi sjekke med et enkelt api kall som returnerer alle NAV-Mac serienummer.
3. Linux maskiner vil jeg selv håndtere inntil videre for de kildene vi har "tilgengelig" er upraktiske.

**Comment by sechmann** [comment]
no serial list available, let issue resurface if it becomes an relevant
