### ISSUE TITLE
Access to Jenkinses

### ISSUE THREAD

**Issue by jhrv** [nais/device#74]
should be one gateway pr jenkins with own access group

**Comment by toby1knby** [comment]
Noticing that this topic might need some attention. Is this * necessary or could it be solved as previous solution in navtunnel was?
*  _"should be one gateway pr jenkins with own access group"_ 

The group where users have requested access could be reused.

**Comment by kmriise** [comment]
Just giving notice that if navtunnel is getting deprecated, we really need access to jenkins for some legacy applications

**Comment by sechmann** [comment]
solved in https://github.com/nais/naisdevice-terraform/commit/d1e90a28015f20e341dbc2f0410e232c7054752b
