### ISSUE TITLE
Access to HR-services (minwintid.adeo.no + agresso.adeo.no)

### ISSUE THREAD

**Issue by jhrv** [nais/device#86]

**Comment by toby1knby** [comment]
Duplicate of #142

**Comment by sechmann** [comment]
Need BigIP APM exception for these (Terje)

**Comment by jhrv** [comment]
is this really a duplicate? Isn't it better to open directly to the service through the gateway like we do for the other services? (e.g. logs.adeo.no) @toby1knby

**Comment by sechmann** [comment]
done
