### ISSUE TITLE
Not enough time to get auth url on Windows

### ISSUE THREAD

**Issue by pcmoen** [nais/device#94]
The device-agent tries only three times with a one second interval to get the auth url on Windows. This is often not enough time for Wireguard to start and setup the connection.

> 2020-08-03 11:18:29.31373 - [INFO] - Connect button clicked
> 2020-08-03 11:18:29.31373 - [INFO] - state changed to Bootstrapping...
> 2020-08-03 11:18:29.31373 - [INFO] - Already bootstrapped
> 2020-08-03 11:18:31.31988 - [INFO] - state changed to Authenticating...
> 2020-08-03 11:18:31.31988 - [INFO] - No valid session, authenticating
> 2020-08-03 11:18:31.31988 - [WARNING] - [attempt 0/3]: getting Azure auth URL from apiserver: getting Azure auth URL from apiserver: Get "http://10.255.240.1/authurl": dial tcp 10.255.240.1:80: connectex: Det ble forsøkt en kontaktoperasjon til en vert som ikke kan nås.
> 2020-08-03 11:18:32.32221 - [WARNING] - [attempt 1/3]: getting Azure auth URL from apiserver: getting Azure auth URL from apiserver: Get "http://10.255.240.1/authurl": dial tcp 10.255.240.1:80: connectex: Det ble forsøkt en kontaktoperasjon til en vert som ikke kan nås.
> 2020-08-03 11:18:38.32317 - [WARNING] - [attempt 2/3]: getting Azure auth URL from apiserver: getting Azure auth URL from apiserver: Get "http://10.255.240.1/authurl": context deadline exceeded
> 2020-08-03 11:18:39.32374 - [ERROR] - Authenticating with apiserver: unable to get auth URL from apiserver after 3 attempts
> 2020-08-03 11:18:39.32374 - [INFO] - state changed to Disconnecting...
> 2020-08-03 11:18:39.32435 - [INFO] - state changed to Disconnected

**Comment by sechmann** [comment]
fixed in #95
