### ISSUE TITLE
Some users don't have nav email on their slack profile

### ISSUE THREAD

**Issue by sechmann** [nais/device#96]
Some users have a non nav emails on their slack profiles, and we use Azure AD email to link device owners to devices.

The reason this is a problem is because the slack email is what's synced to Kolide.

**Comment by christeredvartsen** [comment]
It seems that some users have duplicate accounts. I will see if there is a way of merging accounts in Slack. If not, we simply have to deactivate the non-nav.no ones, and force the users over to the nav.no account.

**Comment by christeredvartsen** [comment]
Merging accounts is not possible, but it is possible to temporarily enable changing of emails, then fix the emails on the duplicate accounts.
